name: huisgenot
description: "Een app om de buurt te verbinden"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"


dependencies:
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  custom_map_markers: ^0.0.2+1
  google_maps_flutter: ^2.5.3
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.0.9
  intl: ^0.19.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
